[package]
name = "substrate-test-node"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "substrate-test-node"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.1.4"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
package = "substrate-inherents"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
package = "substrate-transaction-pool"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
package = "substrate-network"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.aura]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura-primitives"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.grandpa]
git = "https://github.com/paritytech/substrate"
package = "substrate-finality-grandpa"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.grandpa-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-finality-grandpa-primitives"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
package = "substrate-client"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
package = "substrate-basic-authorship"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.contracts]
git = "https://github.com/paritytech/substrate"
package = "srml-contracts"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"

[dependencies.test-node-runtime]
path = "runtime"

[build-dependencies]
vergen = "3.0.4"

[build-dependencies.build-script-utils]
git = "https://github.com/paritytech/substrate"
package = "substrate-build-script-utils"
rev = "6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e"
